# Generated by Django 5.2.6 on 2025-11-21 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código único del cupón (ej: DESCUENTO20)', max_length=50, unique=True, verbose_name='Código')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED', 'Monto Fijo')], default='PERCENTAGE', max_length=20, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Si es porcentaje: 10 = 10%. Si es fijo: 1000 = $1000', max_digits=10, verbose_name='Valor del Descuento')),
                ('valid_from', models.DateTimeField(verbose_name='Válido Desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Número máximo de veces que se puede usar. Dejar vacío para ilimitado.', null=True, verbose_name='Límite de Uso')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Descuento')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aplicación')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_applications', to='orders.coupon', verbose_name='Cupón')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Cupón Aplicado',
                'verbose_name_plural': 'Cupones Aplicados',
                'unique_together': {('order', 'coupon')},
            },
        ),
    ]
