# Generated by Django 5.2.6 on 2025-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=3, unique=True, verbose_name='SKU'),
        ),
    ]
