# Generated by Django 5.2.6 on 2025-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Orden Creada'), ('ORDER_STATUS_CHANGED', 'Estado de Orden Cambiado'), ('REVIEW_CREATED', 'Reseña Creada'), ('REVIEW_APPROVED', 'Reseña Aprobada'), ('GENERAL', 'General')], default='GENERAL', max_length=50, verbose_name='Tipo'),
        ),
    ]
