# Generated by Django 5.2.6 on 2025-09-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('Especie', models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato'), ('HAMSTERS', 'Hamsters'), ('OTHER', 'Otro')], default='DOG', max_length=10, verbose_name='Especie')),
                ('Raza', models.CharField(blank=True, max_length=80, verbose_name='Raza')),
                ('Edad_Años', models.PositiveIntegerField(default=0, verbose_name='Edad (años)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_Vacunado', models.BooleanField(default=False, verbose_name='Vacunado')),
                ('is_castrado', models.BooleanField(default=False, verbose_name='Esterilizado')),
                ('Estado', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PENDING', 'En Proceso'), ('ADOPTED', 'Adoptado')], default='AVAILABLE', max_length=12, verbose_name='Estado')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('Mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, verbose_name='Procesada')),
                ('Mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='adoption.mascota')),
            ],
        ),
    ]
